---
title: "R Notebook"
output: html_notebook
---

```{r}
library(microbenchmark)
```

```{r}
my.fun01 <- function(x) {
  y <- numeric()
  for (i in seq(along.with = x[-1])) {
    y[i] <- x[i] * x[i+1] / log10(123456)
  }
y
}
```

```{r}
microbenchmark(my.fun01(runif(1e3)))
```

```{r}
my.fun02 <- function(x) {
  y <- numeric(length(x))
  for (i in seq(along.with = x[-1])) {
    y[i] <- x[i] * x[i+1] / log10(123456)
  }
y
}
```

```{r}
microbenchmark(my.fun02(runif(1e3)))
```


```{r}
my.fun03 <- function(x) {
  y <- numeric(length(x))
  k <- log10(123456)
  for (i in seq(along.with = x[-1])) {
    y[i] <- x[i] * x[i+1] / k
  }
y
}
```

```{r}
microbenchmark(my.fun03(runif(1e3)))
```

```{r}
my.fun04 <- function(x) {
  i <- seq(along.with = x[-1])
  x[i] * x[i+1] / log10(123456)
}
```

```{r}
microbenchmark(my.fun04(runif(1e3)))
```

```{r}
col <- 100
row <- 100
df <- data.frame(a = 1:row)
for (i in 2:col)
  df <- cbind(df, 1:row)
df
```

```{r}
col <- 100
row <- 100
microbenchmark({
df <- data.frame(a = 1:row)
for (i in 2:col)
  df <- cbind(df, 1:row)
})
```

```{r}
my.fun11(100,100)
```

